SAMPLE_EVENT = {
    "resource": "/{proxy+}",
    "path": "/0",
    "httpMethod": "POST",
    "headers": {
        "Accept": "*/*",
        "CloudFront-Forwarded-Proto": "https",
        "CloudFront-Is-Desktop-Viewer": "true",
        "CloudFront-Is-Mobile-Viewer": "false",
        "CloudFront-Is-SmartTV-Viewer": "false",
        "CloudFront-Is-Tablet-Viewer": "false",
        "CloudFront-Viewer-ASN": "5645",
        "CloudFront-Viewer-Country": "CA",
        "content-type": "application/json",
        "Host": "86vdfzpw1h.execute-api.us-east-1.amazonaws.com",
        "User-Agent": "curl/7.68.0",
        "Via": "2.0 2abaa6585800272f03e152fa41c7b7b6.cloudfront.net (CloudFront)",
        "X-Amz-Cf-Id": "06r2lBj6j2vH9ShKLWYPrSApc2kkJpPbwtuPhHRd0EhoLL45MUyahw==",
        "X-Amzn-Trace-Id": "Root=1-637da3b3-45378e52277e4ee01a93b1b5",
        "X-Forwarded-For": "198.84.222.60, 64.252.143.135",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https",
    },
    "multiValueHeaders": {
        "Accept": ["*/*"],
        "CloudFront-Forwarded-Proto": ["https"],
        "CloudFront-Is-Desktop-Viewer": ["true"],
        "CloudFront-Is-Mobile-Viewer": ["false"],
        "CloudFront-Is-SmartTV-Viewer": ["false"],
        "CloudFront-Is-Tablet-Viewer": ["false"],
        "CloudFront-Viewer-ASN": ["5645"],
        "CloudFront-Viewer-Country": ["CA"],
        "content-type": ["application/json"],
        "Host": ["86vdfzpw1h.execute-api.us-east-1.amazonaws.com"],
        "User-Agent": ["curl/7.68.0"],
        "Via": ["2.0 2abaa6585800272f03e152fa41c7b7b6.cloudfront.net (CloudFront)"],
        "X-Amz-Cf-Id": ["06r2lBj6j2vH9ShKLWYPrSApc2kkJpPbwtuPhHRd0EhoLL45MUyahw=="],
        "X-Amzn-Trace-Id": ["Root=1-637da3b3-45378e52277e4ee01a93b1b5"],
        "X-Forwarded-For": ["198.84.222.60, 64.252.143.135"],
        "X-Forwarded-Port": ["443"],
        "X-Forwarded-Proto": ["https"],
    },
    "queryStringParameters": None,
    "multiValueQueryStringParameters": None,
    "pathParameters": {"proxy": "0"},
    "stageVariables": None,
    "requestContext": {
        "resourceId": "6hd0ep",
        "resourcePath": "/{proxy+}",
        "httpMethod": "POST",
        "extendedRequestId": "cCaEEExtoAMFnVg=",
        "requestTime": "23/Nov/2022:04:38:11 +0000",
        "path": "/test/0",
        "accountId": "788393344127",
        "protocol": "HTTP/1.1",
        "stage": "test",
        "domainPrefix": "86vdfzpw1h",
        "requestTimeEpoch": 1669178291447,
        "requestId": "245cfea2-3faf-49bd-8895-a59deec6081f",
        "identity": {
            "cognitoIdentityPoolId": None,
            "accountId": None,
            "cognitoIdentityId": None,
            "caller": None,
            "sourceIp": "198.84.222.60",
            "principalOrgId": None,
            "accessKey": None,
            "cognitoAuthenticationType": None,
            "cognitoAuthenticationProvider": None,
            "userArn": None,
            "userAgent": "curl/7.68.0",
            "user": None,
        },
        "domainName": "86vdfzpw1h.execute-api.us-east-1.amazonaws.com",
        "apiId": "86vdfzpw1h",
    },
    "body": '{"service_name": "kong-service"}',
    "isBase64Encoded": False,
}
